site:
  title: Zeno Docs
  structure:
    - type: section
      key: section-1
      title: Zeno Docs
      path: zeno-docs
      default: true
      children:
        - type: space
          key: space-1
          title: Docs
          path: docs
          default: true
          content:
            directory: ""
    - type: section
      key: section-2
      title: Test
      path: test
      draft: true
      children:
        - type: space
          key: space-2
          title: Test
          path: untitled
          default: true
          draft: true
          content:
            directory: ""
