site:
  title: Site Git Sync
  structure:
    - type: section
      key: section-1
      title: Site Git Sync
      path: site-git-sync
      default: true
      children:
        - type: space
          key: space-1
          title: Docs
          path: docs
          default: true
          content:
            directory: ""
    - type: section
      key: section-2
      title: Untitled
      path: untitled
      draft: true
      children:
        - type: space
          key: space-2
          title: Untitled
          path: untitled
          default: true
          draft: true
          content:
            directory: ""
    - type: section
      key: section-3
      title: Untitled
      path: untitled-1
      draft: true
      children:
        - type: space
          key: space-3
          title: Untitled
          path: untitled
          default: true
          draft: true
          content:
            directory: ""
    - type: section
      key: section-4
      title: Untitled
      path: untitled-2
      draft: true
      children:
        - type: space
          key: space-4
          title: Untitled
          path: untitled
          default: true
          draft: true
          content:
            directory: ./untitled-2/untitled
    - type: section
      key: section-5
      title: Untitled
      path: untitled-3
      draft: true
      children:
        - type: space
          key: space-5
          title: Untitled
          path: untitled
          default: true
          draft: true
          content:
            directory: ./untitled-3/untitled
